post http://localhost:3000/register/
content-type:application/json

{
  "username": "richard_garuda",
  "password": "ricy143",
  "name": "Richard garuda",
  "gender": "male"
}

post http://localhost:3000/login/
content-type:application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

get http://localhost:3000/user/tweets/feed/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJuYW1lIjoiSm9lIEJpZGVuIiwidXNlcm5hbWUiOiJKb2VCaWRlbiIsInBhc3N3b3JkIjoiJDJiJDEwJDJhcmU2QmE2OW9pL0NhaTRhVC9WTS50N0FPN1RzUXgvLk9nei43WEc0cWp1TWlsMHY4MGFxIiwiZ2VuZGVyIjoibWFsZSIsImlhdCI6MTcyMTQ0OTAwOH0.8odW6VLtGykeNzieX8ROqH7eKsaOIWlpQbQTHGm1vXs

get http://localhost:3000/user/following/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJuYW1lIjoiSm9lIEJpZGVuIiwidXNlcm5hbWUiOiJKb2VCaWRlbiIsInBhc3N3b3JkIjoiJDJiJDEwJDJhcmU2QmE2OW9pL0NhaTRhVC9WTS50N0FPN1RzUXgvLk9nei43WEc0cWp1TWlsMHY4MGFxIiwiZ2VuZGVyIjoibWFsZSIsImlhdCI6MTcyMTQ0OTAwOH0.8odW6VLtGykeNzieX8ROqH7eKsaOIWlpQbQTHGm1vXs


get http://localhost:3000/user/followers/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJuYW1lIjoiSm9lIEJpZGVuIiwidXNlcm5hbWUiOiJKb2VCaWRlbiIsInBhc3N3b3JkIjoiJDJiJDEwJDJhcmU2QmE2OW9pL0NhaTRhVC9WTS50N0FPN1RzUXgvLk9nei43WEc0cWp1TWlsMHY4MGFxIiwiZ2VuZGVyIjoibWFsZSIsImlhdCI6MTcyMTQ0OTAwOH0.8odW6VLtGykeNzieX8ROqH7eKsaOIWlpQbQTHGm1vXs


get http://localhost:3000/tweets/1/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzE1ODU1NjEzfQ.eI_vWckh6p0hmPMctMyYJvN5_cBP29PTvDVWi_lDkcI

get http://localhost:3000/tweets/2/likes/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzE1ODU1NjEzfQ.eI_vWckh6p0hmPMctMyYJvN5_cBP29PTvDVWi_lDkcI

get http://localhost:3000/tweets/2/replies/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzE1ODU1NjEzfQ.eI_vWckh6p0hmPMctMyYJvN5_cBP29PTvDVWi_lDkcI

get http://localhost:3000/user/tweets/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzE1ODU1NjEzfQ.eI_vWckh6p0hmPMctMyYJvN5_cBP29PTvDVWi_lDkcI


post http://localhost:3000/user/tweets/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzE1ODU1NjEzfQ.eI_vWckh6p0hmPMctMyYJvN5_cBP29PTvDVWi_lDkcI
content-type:application/json

{
   "tweet": "The Mornings..."
}

delete http://localhost:3000/tweets/12/
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzE1ODU1NjEzfQ.eI_vWckh6p0hmPMctMyYJvN5_cBP29PTvDVWi_lDkcI